input {
  tcp {
    port => 5044
    codec => json_lines {
      charset => "UTF-8"
    }
  }
}

filter {
  mutate {
    add_field => { "[@metadata][source]" => "app-socket" }
    
  }
  
  grok {
	match => {
		"message" => 'headers="(?<headers>.+?)"\s+httpMethod="(?<http_method>.+?)"\s+pathVariables="(?<path_variables>.+?)"\s+queryParams="(?<query_params>.+?)"\s+requestBody="(?<request_body>.+?)"\s+requestId="(?<request_id>.+?)"\s+responseBody="(?<response_body>.*?)"\s+timestamp="(?<timestamp>.+?)"\s+url="(?<request_url>.+?)"'
	}
  }
  mutate {
	lowercase => [ "http_method" ]
  }
}

output {
  elasticsearch {
    hosts => ["http://localhost:9200"]
    index => "products-ws-%{+YYYY.MM.dd}"
  }
  
  stdout {
    codec => rubydebug
  }
}